[package]
name = "solana_vault_cpi"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.28.0"
anchor-gen = "=0.3.1"


[package.metadata.cargo-machete]
ignored = ["anchor-lang"] 